### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidfetter** [uptimejp/postgres-toolkit#2]
You will get more traction with this if you change to a more liberal license like the one PostgreSQL itself uses, or MIT, or 2-clause BSD.

**Comment by schemaczar** [comment]
Completely agree - GPL v2 is viral.  I won't expose my employer by downloading.

**Comment by snaga** [comment]
I agree with that choosing a license could be one of the consoderations when developing software and open-sourcing it.

I *always* have several options for choosing a license as my own decision, and I thought GPL2 would not be any obstacle for (most of) the potential users *in this case*. This is just a tiny, script-based toolkit. If there is some particular obstacles for the users, I may reconsider the license.

If you don't like GPL2, I understand it is sad thing, but it's your choice. I don't blame you. But I still believe in the power of GPL because I grew up with Linux and other GPL software, and took advantages of them.

So, I have decided choosing GPL2 in this case as my decision.

Thanks,

**Comment by davidfetter** [comment]
No one was questioning your right or ability to choose any license you wish.

I would nevertheless like you to reconsider in view of users and contributors.

When someone working at a place less friendly than mine to the GPL, they run into obstacles, frequently ones surmountable only by changing employers.  When people need to consult the legal department and go through a protracted and uncertain process in order just to download the software, they can and mostly will simply avoid doing it.

Without those users, your potential contributor pool shrinks.  Then it shrinks at least one other way.  As a potential contributor, I need to explain to the legal department why I am not handing over IP to a potential competitor.  This task is a good bit easier to accomplish when the license is free.

As to your growing up on Linux, that may well be, but you've made your career not on Linux but on PostgreSQL, which very consciously and specifically used a more liberal license, one whose nature made a good many things you've done possible.  If you doubt me, consult your previous employers as to their policies on contributing to a GPL project whose copyrights are held by others vs. a MIT- or BSD-licensed one.
